FROM openjdk:8-jre-alpine

ARG DIRECTORY
ARG DEPENDENCIES
ARG JAR_FILE
WORKDIR ${DIRECTORY}

COPY target/${DEPENDENCIES} ${DEPENDENCIES}
COPY target/${JAR_FILE} ${JAR_FILE}

ENTRYPOINT ["/usr/bin/java", "-jar", ${JAR_FILE}]
EXPOSE 8080